<?php

namespace projetGSB\projetGsbBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtatLigneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatLigneRepository extends EntityRepository
{
}
