<?php

namespace projetGSB\projetGsbBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Request;


/**
 * FicheFraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheFraisRepository extends EntityRepository {

    public function invoiceVisitorFilter($data, $idUtilisateur, $etatEnCours) {
       
        $qb = $this->createQueryBuilder('f');
            
        if ($idUtilisateur != '') {
            $qb->andWhere('f.Utilisateur = :idUtilisateur')
                ->setParameter('idUtilisateur', $idUtilisateur);
        }
         
        if($data['mois'] != '') {
            $qb ->andWhere('SUBSTRING(f.date,6,2) = :mois')
                    ->setParameter('mois', $data['mois']);
        }
        
        if($data['annee'] != '') {
            $qb ->andWhere('SUBSTRING(f.date,1,4) = :annee')
                    ->setParameter('annee', $data['annee']);
        }
       
        if ($data['etat'] != '') {
            $qb->andWhere('f.etat = :etat')
                    ->setParameter('etat', $data['etat']);
        }else{
            $qb->andWhere('f.etat != :etat')
                ->setParameter('etat', $etatEnCours);
        }

        return $qb->getQuery()
                    ->getResult();
    }

    public function invoiceNameFilter($data, $etat)
    {
        $qb = $this->createQueryBuilder('f')->join('f.Utilisateur', 'v', 'WITH', 'v.id = f.Utilisateur');
        
        if ($etat != '') {
            $qb->andWhere('f.etat = :etat')
                ->setParameter('etat', $etat);    
        }

        if ($data['nom'] != ''){
            $qb->andWhere('v.nom = :nom')
                    ->setParameter('nom' , $data['nom']);
        }

        return $qb->getQuery()
                    ->getResult();
            
    }

    public function completeFormFilter($data, $etat1, $etat2)
    {
        $qb = $this->createQueryBuilder('f')->join('f.Utilisateur', 'v', 'WITH', 'v.id = f.Utilisateur')
            ->Where('f.etat = :etat1 OR f.etat = :etat2')
                ->setParameter('etat1', $etat1)
                ->setParameter('etat2', $etat2);

         if ($data['etat'] != '') {
            $qb->andWhere('f.etat = :etat')
                ->setParameter('etat', $data['etat']);    
        }

        if ($data['nom'] != ''){
            $qb->andWhere('v.nom = :nom')
                    ->setParameter('nom' , $data['nom']);
        }

         if($data['mois'] != '') {
            $qb ->andWhere('SUBSTRING(f.date,6,2) = :mois')
                    ->setParameter('mois', $data['mois']);
        }
        
        if($data['annee'] != '') {
            $qb ->andWhere('SUBSTRING(f.date,1,4) = :annee')
                    ->setParameter('annee', $data['annee']);
        }
       
        if ($data['etat'] != '') {
            $qb->andWhere('f.etat = :etat')
                    ->setParameter('etat', $data['etat']);
        }

        return $qb->getQuery()
                    ->getResult();
    }

}
