utilisateur:
    path:     /
    defaults: { _controller: "projetGSBprojetGsbBundle:Utilisateur:index" }

utilisateur_show:
    path:     /{id}/show
    defaults: { _controller: "projetGSBprojetGsbBundle:Utilisateur:show" }

utilisateur_new:
    path:     /new
    defaults: { _controller: "projetGSBprojetGsbBundle:Utilisateur:new" }

utilisateur_create:
    path:     /create
    defaults: { _controller: "projetGSBprojetGsbBundle:Utilisateur:create" }
    requirements: { _method: post }

utilisateur_edit:
    path:     /{id}/edit
    defaults: { _controller: "projetGSBprojetGsbBundle:Utilisateur:edit" }

utilisateur_update:
    path:     /{id}/update
    defaults: { _controller: "projetGSBprojetGsbBundle:Utilisateur:update" }
    requirements: { _method: post|put }

utilisateur_delete:
    path:     /{id}/delete
    defaults: { _controller: "projetGSBprojetGsbBundle:Utilisateur:delete" }
    requirements: { _method: post|delete }
